// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMZBS0aoW7_3wLs9AMlbF1EtMNxt_3k2E',
    appId: '1:418140239070:web:e534656d18292b1c1e3e4f',
    messagingSenderId: '418140239070',
    projectId: 'appfortesting-b4bf2',
    authDomain: 'appfortesting-b4bf2.firebaseapp.com',
    databaseURL: 'https://appfortesting-b4bf2-default-rtdb.firebaseio.com',
    storageBucket: 'appfortesting-b4bf2.appspot.com',
    measurementId: 'G-G05PF3843V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbeG8wm-MWYdzhDUxZpJw5xI8C8yFM36U',
    appId: '1:418140239070:android:c8b986b3cc7106e61e3e4f',
    messagingSenderId: '418140239070',
    projectId: 'appfortesting-b4bf2',
    databaseURL: 'https://appfortesting-b4bf2-default-rtdb.firebaseio.com',
    storageBucket: 'appfortesting-b4bf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN3xzlICwxmXFSNtnJyE3t61PVtKmcCww',
    appId: '1:418140239070:ios:7c5f76c21053d3af1e3e4f',
    messagingSenderId: '418140239070',
    projectId: 'appfortesting-b4bf2',
    databaseURL: 'https://appfortesting-b4bf2-default-rtdb.firebaseio.com',
    storageBucket: 'appfortesting-b4bf2.appspot.com',
    iosClientId: '418140239070-i7i9b0iipaknhp2fbcaomvh7skt8ph5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
